#!/usr/bin/env bash

if [ $# -lt 2 ]
then
    printf "%s <KEY> <SIGFILE>\n\nVerify that KEY has signed SIGFILE.\n\n" "$(basename $0)"
    exit 0
fi

keyring=$(mktemp --tmpdir yverify-XXXXXX)
gpg --no-default-keyring --keyring "$keyring" --import "$1"
gpg --no-default-keyring --keyring "$keyring" --verify "$2"
rm -f -- "$keyring"
